
/* Drop Tables */

DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE PROJECT.ADMINATOR CASCADE CONSTRAINTS;
DROP TABLE PROJECT.REVIEW CASCADE CONSTRAINTS;
DROP TABLE PROJECT.COMMEMBER CASCADE CONSTRAINTS;
DROP TABLE PROJECT.RESTAURANT CASCADE CONSTRAINTS;
DROP TABLE PROJECT.STAY CASCADE CONSTRAINTS;
DROP TABLE PROJECT.TOUR CASCADE CONSTRAINTS;
DROP TABLE PROJECT.ENTMEMBER CASCADE CONSTRAINTS;
DROP TABLE PROJECT.FESTIVAL CASCADE CONSTRAINTS;
DROP TABLE PROJECT.NOTICE CASCADE CONSTRAINTS;
DROP TABLE PROJECT.PACKLIST CASCADE CONSTRAINTS;
DROP TABLE PROJECT.PACKORDER CASCADE CONSTRAINTS;
DROP TABLE PROJECT.QNA CASCADE CONSTRAINTS;
DROP TABLE PROJECT.TEST CASCADE CONSTRAINTS;
DROP TABLE PROJECT.EVENT CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE PROJECT.ADMINATOR_SEQ;
DROP SEQUENCE PROJECT.COMMEMBER_SEQ;
DROP SEQUENCE PROJECT.ENTMEMBER_SEQ;
DROP SEQUENCE PROJECT.FES_SEQ;
DROP SEQUENCE PROJECT.GOODPACKAGE_SEQ;
DROP SEQUENCE PROJECT.NOTICE_SEQ;
DROP SEQUENCE PROJECT.PACKLIST_SEQ;
DROP SEQUENCE PROJECT.PACKORDER_SEQ;
DROP SEQUENCE PROJECT.RESTAURANT_SEQ;
DROP SEQUENCE PROJECT.REVIEW_SEQ;
DROP SEQUENCE PROJECT.STAY_SEQ;
DROP SEQUENCE PROJECT.TEST_SEQ;
DROP SEQUENCE PROJECT.TOUR_SEQ;
DROP SEQUENCE PROJECT.EVENT_SEQ;




/* Create Sequences */

CREATE SEQUENCE PROJECT.ADMINATOR_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 0 NOCACHE;
CREATE SEQUENCE PROJECT.COMMEMBER_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 0 NOCACHE;
CREATE SEQUENCE PROJECT.ENTMEMBER_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 0 NOCACHE;
CREATE SEQUENCE PROJECT.FES_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 0 NOCACHE;
CREATE SEQUENCE PROJECT.GOODPACKAGE_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 0 NOCACHE;
CREATE SEQUENCE PROJECT.NOTICE_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 0 NOCACHE;
CREATE SEQUENCE PROJECT.PACKLIST_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 6 NOCACHE;
CREATE SEQUENCE PROJECT.PACKORDER_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 5 NOCACHE;
CREATE SEQUENCE PROJECT.RESTAURANT_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 2 NOCACHE;
CREATE SEQUENCE PROJECT.REVIEW_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 2 NOCACHE;
CREATE SEQUENCE PROJECT.STAY_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 2 NOCACHE;
CREATE SEQUENCE PROJECT.TEST_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 0 NOCACHE;
CREATE SEQUENCE PROJECT.TOUR_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 2 NOCACHE;
CREATE SEQUENCE PROJECT.event_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 0 NOCACHE;


/* Create Tables */

CREATE TABLE EVENT
(
	-- 이벤트 게시판 번호
	-- 
	EVENTNONUM number(4,0) NOT NULL,
	-- 이벤트 게시판 글 제목
	-- 
	EVENTNOTITLE varchar2(20) NOT NULL,
	-- 이벤트 글 작성 날짜
	EVENTNOWRITEDAY date DEFAULT SYSDATE,
	-- 이벤트 글 내용
	EVENTNOCONTENT varchar2(1000) NOT NULL,
	-- 이벤트 글 조회수
	EVENTNOREADCNT number(4,0),
	-- 관리자 번호
	-- 
	EVENTADMNUM number(4,0) NOT NULL,
	PRIMARY KEY (EVENTNONUM)
);


CREATE TABLE PROJECT.ADMINATOR
(
	-- 관리자 번호
	ADMNUM number(4,0) NOT NULL,
	-- 관리자 아이디
	ADMID varchar2(20) NOT NULL,
	-- 관리자 비밀번호
	ADMPASSWD varchar2(20) NOT NULL,
	CONSTRAINT ADMINNUM_PK PRIMARY KEY (ADMNUM)
);


CREATE TABLE PROJECT.COMMEMBER
(
	-- 사용자 번호
	COMNUM number(4,0) NOT NULL,
	-- 사용자 아이디
	COMID varchar2(20) NOT NULL,
	-- 사용자 비밀번호
	COMPASSWD varchar2(20) NOT NULL,
	-- 사용자 이름
	COMNAME varchar2(20) NOT NULL,
	-- 사용자 주민등록번호
	COMSSN number(13) NOT NULL,
	-- 사용자 전화번호
	COMPHONE number(13) NOT NULL,
	-- 사용자 등급
	COMGRADE varchar2(10) NOT NULL,
	-- 사용자 이메일
	COMEMAIL varchar2(40) NOT NULL,
	-- 사용자 주소1
	COMADDR1 varchar2(40) NOT NULL,
	-- 사용자 주소2
	COMADDR2 varchar2(40) NOT NULL,
	-- 사용자 우편번호1
	COMPOST1 number(5,0) NOT NULL,
	-- 사용자 우편번호2
	COMPOST2 number(5,0) NOT NULL,
	CONSTRAINT MBERNUM_PK PRIMARY KEY (COMNUM)
);


CREATE TABLE PROJECT.ENTMEMBER
(
	-- 기업 번호
	ENTNUM number(4,0) NOT NULL,
	-- 기업 아이디
	ENTID varchar2(10) NOT NULL,
	-- 기업 비밀번호
	ENTPASSWD varchar2(20) NOT NULL,
	-- 기업 이름
	ENTNAME varchar2(20) NOT NULL,
	-- 기업 지역위치
	-- 
	ENTLOCATION varchar2(500) NOT NULL,
	-- 기업 전화번호
	ENTPHONE number(13) NOT NULL,
	-- 업주 핸드폰 번호
	ENTCELLPHONE number(13),
	-- 기업 팩스번호
	ENTFAX number(12) NOT NULL,
	-- 기업 사업자등록번호
	ENTIN number(12) NOT NULL,
	-- 기업 종류(명소,맛집,숙박)
	ENTTYPE varchar2(10) NOT NULL,
	CONSTRAINT SYS_C0011035 PRIMARY KEY (ENTNUM)
);


CREATE TABLE PROJECT.FESTIVAL
(
	-- 축제 번호
	-- 
	FESNUM number(7,0) NOT NULL,
	-- 축제 이름
	FESNAME varchar2(20),
	-- 축제 전화번호
	FESPHONE number,
	-- 축제 지역
	FESLOCATION varchar2(20) NOT NULL,
	-- 축제 가격
	FESPRICE number(10,0),
	-- 축제 제목
	FESTITLE varchar2(50),
	-- 축제 내용
	FESCONTENT varchar2(1000),
	-- 축제 글쓴 날짜
	FESWRITEDAY date DEFAULT SYSDATE,
	-- 축제 댓글 수
	FESREADCNT number(10,0) DEFAULT 0,
	-- 축제 이미지
	FESIMAGE varchar2(500),
	-- 축제 이미지 중복시
	FESIMAGECLONE varchar2(500),
	-- 축제 사이트
	FESSITE varchar2(500),
	-- 축제 시즌
	FESSEASON varchar2(20),
	-- 축제 주소
	FESADDR varchar2(50 char),
	CONSTRAINT SYS_C0011798 PRIMARY KEY (FESNUM)
);


CREATE TABLE PROJECT.NOTICE
(
	-- 게시판 번호
	NONUM number(4,0) NOT NULL,
	-- 게시판 글 제목
	NOTITLE varchar2(20) NOT NULL,
	-- 공지사항 글 작성날짜
	NOWRITEDAY date DEFAULT SYSDATE,
	-- 공지사항 글 내용
	NOCONTENT varchar2(1000) NOT NULL,
	-- 공지사항 글 조회수
	NOREADCNT number(4,0) DEFAULT 0,
	-- 관리자 번호
	ADMNUM number(4,0) NOT NULL,
	CONSTRAINT SYS_C0011061 PRIMARY KEY (NONUM)
);


CREATE TABLE PROJECT.PACKLIST
(
	PACKLISTNUM number(4,0) NOT NULL,
	TYPE varchar2(50),
	DAY number(19,0),
	PACKORDERNUM number(4,0) NOT NULL,
	COMNUM number(4,0) NOT NULL,
	TYPENUM number(10,0),
	STATE number(2,0),
	ENDDAY date,
	CONSTRAINT SYS_C0012258 PRIMARY KEY (PACKLISTNUM)
);


CREATE TABLE PROJECT.PACKORDER
(
	PACKORDERNUM number(4,0) NOT NULL,
	STARTDAY date NOT NULL,
	ENDDAY date NOT NULL,
	PACKNAME varchar2(500) NOT NULL,
	ADULT number(4,0) NOT NULL,
	KID number(4,0) NOT NULL,
	PAYMENT varchar2(30) NOT NULL,
	PRICE number(19,0) NOT NULL,
	COMNUM number(4,0) NOT NULL,
	STATE number(2,0),
	CONSTRAINT SYS_C0012254 PRIMARY KEY (PACKORDERNUM)
);


CREATE TABLE PROJECT.QNA
(
	-- 질답 번호
	QNANUM number NOT NULL,
	-- 질답 글 제목
	QNATITLE varchar2(20) NOT NULL,
	-- 질답 글 내용
	QNACONTENT varchar2(80) NOT NULL,
	-- 질답 글 작성 날짜
	QNAWRITEDAY date DEFAULT SYSDATE,
	-- 질답 글 조회수
	QNAREADCNT number(10,0) DEFAULT 0,
	CONSTRAINT SYS_C0011436 PRIMARY KEY (QNANUM)
);


CREATE TABLE PROJECT.RESTAURANT
(
	-- 음식점 번호
	RESTNUM number(4,0) NOT NULL,
	-- 음식점 종류
	RESTTYPE varchar2(50) NOT NULL,
	-- 음식점 이름
	RESTNAME varchar2(50) NOT NULL,
	-- 음식점 지역위치
	RESTLOCATION varchar2(200) NOT NULL,
	-- 음식점 가격
	RESTADULTPRICE number(10,0) DEFAULT 0,
	-- 음식점 전화번호
	RESTPHONE number(12) NOT NULL,
	-- 음식점 글 제목
	RESTTITLE varchar2(50) NOT NULL,
	-- 음식점 글 내용
	RESTCONTENT varchar2(1000) NOT NULL,
	-- 음식점 글 작성 날짜
	RESTWRITEDAY date DEFAULT SYSDATE,
	-- 음식점 글 조회수
	RESTREADCNT number(10,0) DEFAULT 0,
	-- 댓글수
	RESTREPLECNT number(4,0) DEFAULT 0,
	-- 음식점 이미지
	RESTIMAGE varchar2(500) NOT NULL,
	-- 음식점 사이트
	RESTSITE varchar2(500) NOT NULL,
	-- 기업 번호
	ENTNUM number(4,0) NOT NULL,
	-- 음식점 좋아요 카운트
	RESTGOODS number(10,0) DEFAULT 0,
	-- 음식점 이미지 중복시
	RESTIMAGECLONE varchar2(500),
	-- 음식점 도로명 주소
	RESTADDR1 varchar2(500 char),
	-- 음식점 지번 주소
	RESTADDR2 varchar2(500 char),
	RESTKIDPRICE number(10,0),
	CONSTRAINT SYS_C0011039 PRIMARY KEY (RESTNUM)
);


CREATE TABLE PROJECT.REVIEW
(
	PACKREVIEWNUM number(10,0) NOT NULL,
	PACKTITLE varchar2(50 char),
	PACKCONTENT varchar2(1000 char),
	PACKREVIEWWRITEDAY date DEFAULT sysdate,
	PACKREVIEWGOODS number(10,0) DEFAULT 0,
	PACKORDERNUM number(4,0),
	-- 사용자 번호
	COMNUM number(4,0),
	PACKREVIEWRCNT number(10,0) DEFAULT 0,
	CONSTRAINT PK_PACKREVIEWNUM PRIMARY KEY (PACKREVIEWNUM)
);


CREATE TABLE PROJECT.STAY
(
	-- 숙박업소 번호
	STAYNUM number(7,0) NOT NULL,
	-- 숙박업소 종류
	STAYTYPE varchar2(50 char) NOT NULL,
	-- 숙박업소 이름
	STAYNAME varchar2(50 char) NOT NULL,
	-- 숙박업소 지역위치
	STAYLOCATION varchar2(200) NOT NULL,
	-- 숙박업소 등급
	STAYGRADE varchar2(20 char) NOT NULL,
	-- 숙박업소 어른 가격
	STAYADULTPRICE number(10,0) DEFAULT 0,
	-- 숙박업소 어린이 가격
	STAYKIDPRICE number(10,0),
	-- 숙박업소 전화번호
	STAYPHONE number(13) NOT NULL,
	-- 숙박업소 글 제목
	STAYTITLE varchar2(50) NOT NULL,
	-- 숙박업소 글 내용
	STAYCONTENT varchar2(1000) NOT NULL,
	-- 숙박업소 글 작성 날짜
	STAYWRITEDAY date DEFAULT SYSDATE,
	-- 숙박업소 글 조회수
	STAYREADCNT number(10,0) DEFAULT 0,
	-- 숙박업소 댓글수
	STAYREPLECNT number(5,0) DEFAULT 0,
	-- 숙박업소 이미지
	STAYIMAGE varchar2(500) NOT NULL,
	-- 숙박업소 사이트
	STAYSITE varchar2(500) NOT NULL,
	-- 기업 번호
	ENTNUM number(4,0) NOT NULL,
	-- 숙박업소 좋아요 카운트
	STAYGOODS number(10,0) DEFAULT 0,
	-- 숙박업소 이미지 중복시
	STAYIMAGECLONE varchar2(500),
	-- 숙박업소 도로명 주소
	STAYADDR1 varchar2(500),
	-- 숙박업소 지번 주소
	STAYADDR2 varchar2(500 char),
	CONSTRAINT SYS_C0011042 PRIMARY KEY (STAYNUM)
);


CREATE TABLE PROJECT.TEST
(
	REPLY_ID number NOT NULL,
	ARTICLE_ID number,
	MEMBER_ID number,
	DESCRIPTION varchar2(50 char),
	GROUP_ID number DEFAULT 0    NOT NULL,
	PARENT_REPLY_ID number DEFAULT 0    NOT NULL,
	DEPTH number DEFAULT 0    NOT NULL,
	ORDER_NO number DEFAULT 0    NOT NULL,
	CONSTRAINT PK_REPLY_ID PRIMARY KEY (REPLY_ID)
);


CREATE TABLE PROJECT.TOUR
(
	-- 관광지 종류
	ATTTYPE varchar2(50) NOT NULL,
	-- 관광지 이름
	ATTNAME varchar2(50) NOT NULL,
	-- 관광지 지역위치
	ATTLOCATION varchar2(200) NOT NULL,
	-- 관광지 어른 가격
	ATTADULTPRICE number(10,0) DEFAULT 0,
	-- 관광지 어린이 가격
	ATTKIDPRICE number(10,0),
	-- 관광지 전화번호
	ATTPHONE varchar2(20) NOT NULL,
	-- 관광지 글 제목
	ATTTITLE varchar2(50) NOT NULL,
	-- 관광지 번호
	ATTNUM number(7,0) NOT NULL,
	-- 관광지 글 내용
	ATTCONTENT varchar2(1000) NOT NULL,
	-- 관광지 글쓴 날짜
	ATTWRITEDAY date DEFAULT SYSDATE,
	-- 관광지 조회수
	ATTREADCNT number(10,0) DEFAULT 0,
	-- 관광지 댓글수
	ATTREPLECNT number(10,0) DEFAULT 0,
	-- 관광지 이미지
	ATTIMAGE varchar2(500) NOT NULL,
	-- 관광지 사이트
	ATTSITE varchar2(500) NOT NULL,
	-- 기업 번호
	ENTNUM number(4,0) NOT NULL,
	-- 좋아요 카운트
	ATTGOODS number(10,0) DEFAULT 0 ,
	-- 이미지 중복시에
	ATTIMAGECLONE varchar2(500),
	-- 관광지 도로명 주소
	ATTADDR1 varchar2(500),
	-- 관광지 지번 주소
	ATTADDR2 varchar2(500 char),
	CONSTRAINT SYS_C0011329 PRIMARY KEY (ATTNUM)
);



/* Create Foreign Keys */

ALTER TABLE PROJECT.REVIEW
	ADD CONSTRAINT FK_COMNUM FOREIGN KEY (COMNUM)
	REFERENCES PROJECT.COMMEMBER (COMNUM)
	ON DELETE SET NULL
;


ALTER TABLE PROJECT.RESTAURANT
	ADD CONSTRAINT SYS_C0011480 FOREIGN KEY (ENTNUM)
	REFERENCES PROJECT.ENTMEMBER (ENTNUM)
;


ALTER TABLE PROJECT.STAY
	ADD CONSTRAINT SYS_C0011481 FOREIGN KEY (ENTNUM)
	REFERENCES PROJECT.ENTMEMBER (ENTNUM)
;


ALTER TABLE PROJECT.TOUR
	ADD CONSTRAINT SYS_C0011482 FOREIGN KEY (ENTNUM)
	REFERENCES PROJECT.ENTMEMBER (ENTNUM)
;


ALTER TABLE PROJECT.REVIEW
	ADD CONSTRAINT FK_PACKORDERNUM FOREIGN KEY (PACKORDERNUM)
	REFERENCES PROJECT.PACKORDER (PACKORDERNUM)
	ON DELETE SET NULL
;



/* Comments */

COMMENT ON COLUMN EVENT.EVENTNONUM IS '이벤트 게시판 번호
';
COMMENT ON COLUMN EVENT.EVENTNOTITLE IS '이벤트 게시판 글 제목
';
COMMENT ON COLUMN EVENT.EVENTNOWWRITEDAY IS '이벤트 글 작성 날짜';
COMMENT ON COLUMN EVENT.EVENTNOCONTENT IS '이벤트 글 내용';
COMMENT ON COLUMN EVENT.EVENTNOREADCNT IS '이벤트 글 조회수';
COMMENT ON COLUMN EVENT.EVENTADMNUM IS '관리자 번호
';
COMMENT ON COLUMN PROJECT.ADMINATOR.ADMNUM IS '관리자 번호';
COMMENT ON COLUMN PROJECT.ADMINATOR.ADMID IS '관리자 아이디';
COMMENT ON COLUMN PROJECT.ADMINATOR.ADMPASSWD IS '관리자 비밀번호';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMNUM IS '사용자 번호';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMID IS '사용자 아이디';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMPASSWD IS '사용자 비밀번호';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMNAME IS '사용자 이름';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMSSN IS '사용자 주민등록번호';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMPHONE IS '사용자 전화번호';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMGRADE IS '사용자 등급';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMEMAIL IS '사용자 이메일';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMADDR1 IS '사용자 주소1';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMADDR2 IS '사용자 주소2';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMPOST1 IS '사용자 우편번호1';
COMMENT ON COLUMN PROJECT.COMMEMBER.COMPOST2 IS '사용자 우편번호2';
COMMENT ON COLUMN PROJECT.ENTMEMBER.ENTNUM IS '기업 번호';
COMMENT ON COLUMN PROJECT.ENTMEMBER.ENTID IS '기업 아이디';
COMMENT ON COLUMN PROJECT.ENTMEMBER.ENTPASSWD IS '기업 비밀번호';
COMMENT ON COLUMN PROJECT.ENTMEMBER.ENTNAME IS '기업 이름';
COMMENT ON COLUMN PROJECT.ENTMEMBER.ENTLOCATION IS '기업 지역위치
';
COMMENT ON COLUMN PROJECT.ENTMEMBER.ENTPHONE IS '기업 전화번호';
COMMENT ON COLUMN PROJECT.ENTMEMBER.ENTCELLPHONE IS '업주 핸드폰 번호';
COMMENT ON COLUMN PROJECT.ENTMEMBER.ENTFAX IS '기업 팩스번호';
COMMENT ON COLUMN PROJECT.ENTMEMBER.ENTIN IS '기업 사업자등록번호';
COMMENT ON COLUMN PROJECT.ENTMEMBER.ENTTYPE IS '기업 종류(명소,맛집,숙박)';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESNUM IS '축제 번호
';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESNAME IS '축제 이름';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESPHONE IS '축제 전화번호';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESLOCATION IS '축제 지역';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESPRICE IS '축제 가격';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESTITLE IS '축제 제목';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESCONTENT IS '축제 내용';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESWRITEDAY IS '축제 글쓴 날짜';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESREADCNT IS '축제 댓글 수';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESIMAGE IS '축제 이미지';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESIMAGECLONE IS '축제 이미지 중복시';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESSITE IS '축제 사이트';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESSEASON IS '축제 시즌';
COMMENT ON COLUMN PROJECT.FESTIVAL.FESADDR IS '축제 주소';
COMMENT ON COLUMN PROJECT.NOTICE.NONUM IS '게시판 번호';
COMMENT ON COLUMN PROJECT.NOTICE.NOTITLE IS '게시판 글 제목';
COMMENT ON COLUMN PROJECT.NOTICE.NOWRITEDAY IS '공지사항 글 작성날짜';
COMMENT ON COLUMN PROJECT.NOTICE.NOCONTENT IS '공지사항 글 내용';
COMMENT ON COLUMN PROJECT.NOTICE.NOREADCNT IS '공지사항 글 조회수';
COMMENT ON COLUMN PROJECT.NOTICE.ADMNUM IS '관리자 번호';
COMMENT ON COLUMN PROJECT.QNA.QNANUM IS '질답 번호';
COMMENT ON COLUMN PROJECT.QNA.QNATITLE IS '질답 글 제목';
COMMENT ON COLUMN PROJECT.QNA.QNACONTENT IS '질답 글 내용';
COMMENT ON COLUMN PROJECT.QNA.QNAWRITEDAY IS '질답 글 작성 날짜';
COMMENT ON COLUMN PROJECT.QNA.QNAREADCNT IS '질답 글 조회수';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTNUM IS '음식점 번호';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTTYPE IS '음식점 종류';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTNAME IS '음식점 이름';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTLOCATION IS '음식점 지역위치';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTADULTPRICE IS '음식점 가격';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTPHONE IS '음식점 전화번호';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTTITLE IS '음식점 글 제목';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTCONTENT IS '음식점 글 내용';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTWRITEDAY IS '음식점 글 작성 날짜';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTREADCNT IS '음식점 글 조회수';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTREPLECNT IS '댓글수';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTIMAGE IS '음식점 이미지';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTSITE IS '음식점 사이트';
COMMENT ON COLUMN PROJECT.RESTAURANT.ENTNUM IS '기업 번호';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTGOODS IS '음식점 좋아요 카운트';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTIMAGECLONE IS '음식점 이미지 중복시';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTADDR1 IS '음식점 도로명 주소';
COMMENT ON COLUMN PROJECT.RESTAURANT.RESTADDR2 IS '음식점 지번 주소';
COMMENT ON COLUMN PROJECT.REVIEW.COMNUM IS '사용자 번호';
COMMENT ON COLUMN PROJECT.STAY.STAYNUM IS '숙박업소 번호';
COMMENT ON COLUMN PROJECT.STAY.STAYTYPE IS '숙박업소 종류';
COMMENT ON COLUMN PROJECT.STAY.STAYNAME IS '숙박업소 이름';
COMMENT ON COLUMN PROJECT.STAY.STAYLOCATION IS '숙박업소 지역위치';
COMMENT ON COLUMN PROJECT.STAY.STAYGRADE IS '숙박업소 등급';
COMMENT ON COLUMN PROJECT.STAY.STAYADULTPRICE IS '숙박업소 어른 가격';
COMMENT ON COLUMN PROJECT.STAY.STAYKIDPRICE IS '숙박업소 어린이 가격';
COMMENT ON COLUMN PROJECT.STAY.STAYPHONE IS '숙박업소 전화번호';
COMMENT ON COLUMN PROJECT.STAY.STAYTITLE IS '숙박업소 글 제목';
COMMENT ON COLUMN PROJECT.STAY.STAYCONTENT IS '숙박업소 글 내용';
COMMENT ON COLUMN PROJECT.STAY.STAYWRITEDAY IS '숙박업소 글 작성 날짜';
COMMENT ON COLUMN PROJECT.STAY.STAYREADCNT IS '숙박업소 글 조회수';
COMMENT ON COLUMN PROJECT.STAY.STAYREPLECNT IS '숙박업소 댓글수';
COMMENT ON COLUMN PROJECT.STAY.STAYIMAGE IS '숙박업소 이미지';
COMMENT ON COLUMN PROJECT.STAY.STAYSITE IS '숙박업소 사이트';
COMMENT ON COLUMN PROJECT.STAY.ENTNUM IS '기업 번호';
COMMENT ON COLUMN PROJECT.STAY.STAYGOODS IS '숙박업소 좋아요 카운트';
COMMENT ON COLUMN PROJECT.STAY.STAYIMAGECLONE IS '숙박업소 이미지 중복시';
COMMENT ON COLUMN PROJECT.STAY.STAYADDR1 IS '숙박업소 도로명 주소';
COMMENT ON COLUMN PROJECT.STAY.STAYADDR2 IS '숙박업소 지번 주소';
COMMENT ON COLUMN PROJECT.TOUR.ATTTYPE IS '관광지 종류';
COMMENT ON COLUMN PROJECT.TOUR.ATTNAME IS '관광지 이름';
COMMENT ON COLUMN PROJECT.TOUR.ATTLOCATION IS '관광지 지역위치';
COMMENT ON COLUMN PROJECT.TOUR.ATTADULTPRICE IS '관광지 어른 가격';
COMMENT ON COLUMN PROJECT.TOUR.ATTKIDPRICE IS '관광지 어린이 가격';
COMMENT ON COLUMN PROJECT.TOUR.ATTPHONE IS '관광지 전화번호';
COMMENT ON COLUMN PROJECT.TOUR.ATTTITLE IS '관광지 글 제목';
COMMENT ON COLUMN PROJECT.TOUR.ATTNUM IS '관광지 번호';
COMMENT ON COLUMN PROJECT.TOUR.ATTCONTENT IS '관광지 글 내용';
COMMENT ON COLUMN PROJECT.TOUR.ATTWRITEDAY IS '관광지 글쓴 날짜';
COMMENT ON COLUMN PROJECT.TOUR.ATTREADCNT IS '관광지 조회수';
COMMENT ON COLUMN PROJECT.TOUR.ATTREPLECNT IS '관광지 댓글수';
COMMENT ON COLUMN PROJECT.TOUR.ATTIMAGE IS '관광지 이미지';
COMMENT ON COLUMN PROJECT.TOUR.ATTSITE IS '관광지 사이트';
COMMENT ON COLUMN PROJECT.TOUR.ENTNUM IS '기업 번호';
COMMENT ON COLUMN PROJECT.TOUR.ATTGOODS IS '좋아요 카운트';
COMMENT ON COLUMN PROJECT.TOUR.ATTIMAGECLONE IS '이미지 중복시에';
COMMENT ON COLUMN PROJECT.TOUR.ATTADDR1 IS '관광지 도로명 주소';
COMMENT ON COLUMN PROJECT.TOUR.ATTADDR2 IS '관광지 지번 주소';



