
/* Drop Tables */

DROP TABLE PROJECT.FESTIVAL CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE PROJECT.FESTIVAL
(
	FESNUM number(7,0) NOT NULL,
	FESNAME varchar2(20),
	FESPHONE number(12),
	FESLOCATION varchar2(20 char) NOT NULL,
	FESPRICE number(10,0),
	FESTITLE varchar2(50 char),
	FESCONTENT varchar2(1000 char),
	FESWRITEDAY date,
	FESREADCNT number(10,0),
	FESIMAGE varchar2(500 char),
	FESSITE varchar2(500 char)
);

/* FES sequence */
CREATE SEQUENCE PROJECT.FES_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 999 START WITH 0 NOCACHE;
