
/* Drop Tables */

DROP TABLE SHOP.BOARD CASCADE CONSTRAINTS;
DROP TABLE SHOP.CART CASCADE CONSTRAINTS;
DROP TABLE SHOP.ORDERINFO CASCADE CONSTRAINTS;
DROP TABLE SHOP.GOODS CASCADE CONSTRAINTS;
DROP TABLE SHOP.MEMBER CASCADE CONSTRAINTS;
DROP TABLE SHOP.MYBOARD CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SHOP.BOARD_SEQ;
DROP SEQUENCE SHOP.CART_SEQ;
DROP SEQUENCE SHOP.MYBOARD_SEQ;
DROP SEQUENCE SHOP.ORDERINFO_SEQ;




/* Create Sequences */

CREATE SEQUENCE SHOP.BOARD_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 41 CACHE 20;
CREATE SEQUENCE SHOP.CART_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 61 CACHE 20;
CREATE SEQUENCE SHOP.MYBOARD_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 21 CACHE 20;
CREATE SEQUENCE SHOP.ORDERINFO_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 CACHE 20;



/* Create Tables */

CREATE TABLE SHOP.BOARD
(
	NUM number(4,0) NOT NULL,
	TITLE varchar2(200 char) NOT NULL,
	AUTHOR varchar2(20 char) NOT NULL,
	CONTENT varchar2(4000 char) NOT NULL,
	WRITEDAY date DEFAULT sysdate,
	READCNT number(4,0) DEFAULT 0
,
	CONSTRAINT SYS_C0010987 PRIMARY KEY (NUM)
);


CREATE TABLE SHOP.CART
(
	NUM number(6) NOT NULL,
	USERID varchar2(10 char),
	GCODE varchar2(20 char) NOT NULL,
	GNAME varchar2(50 char) NOT NULL,
	GPRICE number(6) NOT NULL,
	GSIZE char(1 char) NOT NULL,
	GCOLOR varchar2(10 char) NOT NULL,
	GAMOUNT number(2,0) NOT NULL,
	GIMAGE varchar2(20 char) NOT NULL,
	CONSTRAINT SYS_C0010964 PRIMARY KEY (NUM)
);


CREATE TABLE SHOP.GOODS
(
	GCODE varchar2(20 char) NOT NULL,
	GCATEGORY varchar2(20 char) NOT NULL,
	GNAME varchar2(50 char) NOT NULL,
	GCONTENT varchar2(4000 char) NOT NULL,
	GPRICE number(6) NOT NULL,
	GIMAGE varchar2(20 char) NOT NULL,
	CONSTRAINT SYS_C0010956 PRIMARY KEY (GCODE)
);


CREATE TABLE SHOP.MEMBER
(
	USERID varchar2(10 char) NOT NULL,
	PASSWD varchar2(10 char) NOT NULL,
	USERNAME varchar2(10 char) NOT NULL,
	POST1 varchar2(3 char) NOT NULL,
	POST2 varchar2(3 char) NOT NULL,
	ADDR1 varchar2(500 char) NOT NULL,
	ADDR2 varchar2(500 char) NOT NULL,
	PHONE1 varchar2(3 char) NOT NULL,
	PHONE2 varchar2(4 char) NOT NULL,
	PHONE3 varchar2(4 char) NOT NULL,
	EMAIL1 varchar2(20 char) NOT NULL,
	EMAIL2 varchar2(20 char) NOT NULL,
	CONSTRAINT SYS_C0010947 PRIMARY KEY (USERID)
);


CREATE TABLE SHOP.MYBOARD
(
	NUM number(4,0) NOT NULL,
	TITLE varchar2(100 char) NOT NULL,
	AUTHOR varchar2(10 char) NOT NULL,
	CONTENT varchar2(2000 char),
	WRITEDAY date DEFAULT SYSDATE,
	READCNT number(4,0) DEFAULT 0 ,
	CONSTRAINT MYBOARD_NUM_PK PRIMARY KEY (NUM)
);


CREATE TABLE SHOP.ORDERINFO
(
	NUM number(6) NOT NULL,
	USERID varchar2(10 char),
	GCODE varchar2(20 char) NOT NULL,
	GNAME varchar2(50 char) NOT NULL,
	GPRICE number(6) NOT NULL,
	GSIZE char(1 char) NOT NULL,
	GCOLOR varchar2(10 char) NOT NULL,
	GAMOUNT number(2,0) NOT NULL,
	GIMAGE varchar2(20 char) NOT NULL,
	ORDERNAME varchar2(10 char) NOT NULL,
	POST1 varchar2(3 char) NOT NULL,
	POST2 varchar2(3 char) NOT NULL,
	ADDR1 varchar2(500 char) NOT NULL,
	ADDR2 varchar2(500 char) NOT NULL,
	PHONE varchar2(11 char) NOT NULL,
	PAYMETHOD varchar2(10 char) NOT NULL,
	ORDERDAY date DEFAULT SYSDATE
  ,
	CONSTRAINT SYS_C0010981 PRIMARY KEY (NUM)
);



/* Create Foreign Keys */

ALTER TABLE SHOP.CART
	ADD CONSTRAINT CART_GCODE_FK FOREIGN KEY (GCODE)
	REFERENCES SHOP.GOODS (GCODE)
	ON DELETE CASCADE
;


ALTER TABLE SHOP.ORDERINFO
	ADD CONSTRAINT ORDERINFO_GCODE_FK FOREIGN KEY (GCODE)
	REFERENCES SHOP.GOODS (GCODE)
	ON DELETE CASCADE
;


ALTER TABLE SHOP.CART
	ADD CONSTRAINT CART_USERID_FK FOREIGN KEY (USERID)
	REFERENCES SHOP.MEMBER (USERID)
	ON DELETE CASCADE
;


ALTER TABLE SHOP.ORDERINFO
	ADD CONSTRAINT ORDERINFO_USERID_FK FOREIGN KEY (USERID)
	REFERENCES SHOP.MEMBER (USERID)
	ON DELETE CASCADE
;



